# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{version_fu}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jordan McKible"]
  s.date = %q{2009-08-12}
  s.description = %q{TODO}
  s.email = %q{}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".idea/inspectionProfiles/Project_Default.xml",
     ".idea/inspectionProfiles/profiles_settings.xml",
     "MIT-LICENSE",
     "README.rdoc",
     "RUNNING_UNIT_TESTS",
     "Rakefile",
     "VERSION",
     "lib/version_fu.rb",
     "lib/version_fu/version_fu.rb",
     "test/database.yml",
     "test/fixtures/author.rb",
     "test/fixtures/author_versions.yml",
     "test/fixtures/authors.yml",
     "test/fixtures/page.rb",
     "test/fixtures/page_versions.yml",
     "test/fixtures/pages.yml",
     "test/schema.rb",
     "test/test_helper.rb",
     "test/version_fu_test.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Gemified version of the version_fu plugin.}
  s.test_files = [
    "test/fixtures/author.rb",
     "test/fixtures/page.rb",
     "test/test_helper.rb",
     "test/version_fu_test.rb",
     "test/schema.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
